name: Build and Deploy Sphinx Documentation

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: links
          version: 1.0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build HTML documentation
        run: |
          make html
          find docs -name '*.rst' -exec sed -i '/:linenos:/d' {} +
          sphinx-build -c docs/singlehtml -b singlehtml docs/ build
          links -dump build/index.html | sed -e 's/¶//g' | grep -v Link: > build/html/daisys-api-doc.txt

      - name: Upload HTML documentation
        uses: actions/upload-artifact@v4
        with:
          name: daisys-api-html-docs
          path: build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - name: Download HTML documentation
        uses: actions/download-artifact@v4
        with:
          name: daisys-api-html-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
